### ISSUE TITLE
Nasal runtime error: Yasim Gross Weight

### ISSUE THREAD

**Issue by ghost** [HHS81/ec135#14]
Hi Heiko, 
in the last flightgear version (2017.1.0), there is a nasal runtime error in ec135.nas, because yasim/gross-weight-lbs seems to be defined too late for the system. This makes the aircraft systems not working at all. 
A fix is to replace (Nasal/ec135.nas, line 1040)
	gross_weight_kg.setDoubleValue(gross_weight_lb.getValue() * LB2KG);
by
	gross_weight_kg.setDoubleValue(gross_weight_lb.getValue() or 0 * LB2KG);
to make the nasal independent of the definition time.
Regards
D-ECHO
PS: This also applies to the ec130
PPS: Thanks for this very good helicopter!

**Comment by HHS81** [comment]
Hi,  thanks for the report. There are more helicopter affected. The Bug is due the new property location of yasim/gross-weight. Your fix ist one of the solution, I have another one coming.

**Comment by HHS81** [comment]
Fixed here and on FGAddon. Thanks for the report!

**Comment by ghost** [comment]
Thanks for fixing :D
