### ISSUE TITLE
GTX 330 Transponder

### ISSUE THREAD

**Issue by HHS81** [HHS81/ec135#4]
- [x] color of display should be inverted
- [x] numbers should use property of instrumentation/transponder/...
- [ ] ~~making use of transponder code of Extra500?~~

**Comment by SebDieBln** [comment]
The [transponder code of the Extra500](https://gitlab.com/extra500/extra500/blob/20834ac967fe245c01c11f4421bc9d9ff4d80b2d/Dialogs/radios.xml#L36-49) seems quite basic and not suitable for the EC135.
See #19 for further improvements that will allow to close this issue.

**Comment by HHS81** [comment]
I close this, as the improvements by SebDieBln has been already merged
